# Generated by Django 6.0.3 on 2026-03-17 18:13

import common.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('integrations', '0005_alter_appcredentialaccessaudit_event_type_and_more'),
        ('organizations', '0002_alter_organization_segment_and_more'),
        ('people', '0002_person_bot_conversa_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GmailCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sender_email', models.EmailField(max_length=254)),
                ('credentials_json', common.fields.EncryptedTextField()),
                ('token_json', common.fields.EncryptedTextField()),
                ('scopes', models.JSONField(blank=True, default=list)),
                ('token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_gmail_credentials', to=settings.AUTH_USER_MODEL)),
                ('installation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gmail_credential', to='integrations.organizationappinstallation')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gmail_credentials', to='organizations.organization')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_gmail_credentials', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('sender_email',),
            },
        ),
        migrations.CreateModel(
            name='GmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('subject', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_gmail_templates', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gmail_templates', to='organizations.organization')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_gmail_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='GmailDispatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject_snapshot', models.CharField(max_length=255)),
                ('body_snapshot', models.TextField()),
                ('cc_recipients_snapshot', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('running', 'Em andamento'), ('completed', 'Concluido'), ('completed_with_errors', 'Concluido com erros'), ('failed', 'Falhou')], default='pending', max_length=32)),
                ('total_recipients', models.PositiveIntegerField(default=0)),
                ('processed_recipients', models.PositiveIntegerField(default=0)),
                ('success_recipients', models.PositiveIntegerField(default=0)),
                ('failed_recipients', models.PositiveIntegerField(default=0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('error_summary', models.CharField(blank=True, max_length=255)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_gmail_dispatches', to=settings.AUTH_USER_MODEL)),
                ('installation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gmail_dispatches', to='integrations.organizationappinstallation')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gmail_dispatches', to='organizations.organization')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_gmail_dispatches', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispatches', to='gmail_integration.gmailtemplate')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='GmailDispatchRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email_snapshot', models.EmailField(max_length=254)),
                ('first_name_snapshot', models.CharField(max_length=120)),
                ('last_name_snapshot', models.CharField(max_length=120)),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('sent', 'Enviado'), ('failed', 'Falhou')], default='pending', max_length=16)),
                ('gmail_message_id', models.CharField(blank=True, max_length=255)),
                ('gmail_thread_id', models.CharField(blank=True, max_length=255)),
                ('error_message', models.CharField(blank=True, max_length=255)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('dispatch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='gmail_integration.gmaildispatch')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gmail_dispatch_recipients', to='organizations.organization')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gmail_dispatch_recipients', to='people.person')),
            ],
            options={
                'ordering': ('first_name_snapshot', 'last_name_snapshot', 'email_snapshot'),
                'constraints': [models.UniqueConstraint(fields=('dispatch', 'person'), name='unique_gmail_dispatch_recipient_per_person')],
            },
        ),
        migrations.AddConstraint(
            model_name='gmailtemplate',
            constraint=models.UniqueConstraint(fields=('organization', 'name'), name='unique_gmail_template_name_per_organization'),
        ),
    ]
