# Generated by Django 6.0.3 on 2026-03-17 18:14

import common.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gmail_integration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gmailcredential',
            name='credentials_json',
            field=common.fields.EncryptedTextField(fallback_purposes=('default',), purpose='app-credential'),
        ),
        migrations.AlterField(
            model_name='gmailcredential',
            name='token_json',
            field=common.fields.EncryptedTextField(fallback_purposes=('default',), purpose='app-credential'),
        ),
    ]
