# Generated by Django 6.0.3 on 2026-03-17 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gmail_integration', '0002_alter_gmailcredential_credentials_json_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gmailcredential',
            name='sender_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
    ]
