# Generated by Django 6.0.3 on 2026-03-18 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gmail_integration', '0003_alter_gmailcredential_sender_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='gmaildispatch',
            name='max_delay_seconds',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gmaildispatch',
            name='min_delay_seconds',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='gmaildispatchrecipient',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendente'), ('running', 'Em andamento'), ('sent', 'Enviado'), ('failed', 'Falhou')], default='pending', max_length=16),
        ),
    ]
