# Generated by Django 6.0.3 on 2026-03-18 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gmail_integration', '0004_gmaildispatch_max_delay_seconds_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gmaildispatch',
            name='max_delay_seconds',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='gmaildispatch',
            name='min_delay_seconds',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
