# Generated by Django 6.0.3 on 2026-03-19 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0002_seed_system_groups'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='adminaccesslog',
            new_name='admin_panel_logged__6ddb30_idx',
            old_name='admin_panel_logged__f3c9bb_idx',
        ),
        migrations.RenameIndex(
            model_name='adminaccesslog',
            new_name='admin_panel_session_0539ef_idx',
            old_name='admin_panel_session_7ce835_idx',
        ),
        migrations.RenameIndex(
            model_name='adminaccesslog',
            new_name='admin_panel_user_id_6c1f42_idx',
            old_name='admin_panel_user_id_16b7d2_idx',
        ),
    ]
