# Generated by Django 6.0.3 on 2026-03-16 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='segment',
            field=models.CharField(choices=[('technology', 'Tecnologia'), ('consulting', 'Consultoria'), ('services', 'Servicos'), ('other', 'Outro')], max_length=32),
        ),
        migrations.AlterField(
            model_name='organizationinvite',
            name='status',
            field=models.CharField(choices=[('available', 'Disponivel'), ('used', 'Usado'), ('expired', 'Expirado')], default='available', max_length=16),
        ),
        migrations.AlterField(
            model_name='organizationinvite',
            name='target_role',
            field=models.CharField(choices=[('admin', 'Administrador'), ('user', 'Usuario')], max_length=16),
        ),
        migrations.AlterField(
            model_name='organizationmembership',
            name='role',
            field=models.CharField(choices=[('owner', 'Proprietario'), ('admin', 'Administrador'), ('user', 'Usuario')], default='user', max_length=16),
        ),
    ]
