# Generated by Django 6.0.3 on 2026-03-17 19:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        ('integrations', '0006_update_gmail_catalog_metadata'),
        ('organizations', '0002_alter_organization_segment_and_more'),
        ('people', '0003_person_email_person_email_lookup_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HubSpotPipelineCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hubspot_pipeline_id', models.CharField(max_length=128)),
                ('name', models.CharField(max_length=255)),
                ('object_type', models.CharField(default='deals', max_length=64)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('last_synced_at', models.DateTimeField()),
                ('installation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hubspot_pipelines', to='integrations.organizationappinstallation')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hubspot_pipelines', to='organizations.organization')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='HubSpotDeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hubspot_deal_id', models.CharField(blank=True, db_index=True, default='', max_length=128)),
                ('name', models.CharField(max_length=255)),
                ('amount', models.CharField(blank=True, max_length=64)),
                ('stage_id', models.CharField(blank=True, max_length=128)),
                ('sync_status', models.CharField(choices=[('synced', 'Sincronizado'), ('error', 'Erro')], default='synced', max_length=16)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hubspot_deals', to='companies.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_hubspot_deals', to=settings.AUTH_USER_MODEL)),
                ('installation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hubspot_deals', to='integrations.organizationappinstallation')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hubspot_deals', to='organizations.organization')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_hubspot_deals', to=settings.AUTH_USER_MODEL)),
                ('pipeline', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hubspot_deals', to='hubspot_integration.hubspotpipelinecache')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='HubSpotSyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entity_type', models.CharField(choices=[('company', 'Empresa'), ('person', 'Pessoa'), ('pipeline', 'Pipeline'), ('deal', 'Deal')], max_length=16)),
                ('outcome', models.CharField(choices=[('success', 'Sucesso'), ('error', 'Erro')], max_length=16)),
                ('message', models.CharField(blank=True, max_length=255)),
                ('remote_payload', models.JSONField(blank=True, default=dict)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hubspot_sync_logs', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hubspot_sync_logs', to='companies.company')),
                ('deal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hubspot_sync_logs', to='hubspot_integration.hubspotdeal')),
                ('installation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hubspot_sync_logs', to='integrations.organizationappinstallation')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hubspot_sync_logs', to='organizations.organization')),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hubspot_sync_logs', to='people.person')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddConstraint(
            model_name='hubspotpipelinecache',
            constraint=models.UniqueConstraint(fields=('organization', 'installation', 'hubspot_pipeline_id'), name='unique_hubspot_pipeline_per_installation'),
        ),
        migrations.AddConstraint(
            model_name='hubspotdeal',
            constraint=models.UniqueConstraint(condition=models.Q(('hubspot_deal_id', ''), _negated=True), fields=('organization', 'hubspot_deal_id'), name='unique_hubspot_deal_id_per_organization'),
        ),
    ]
