# Generated by Django 6.0.3 on 2026-03-20 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='importjob',
            new_name='imports_imp_organiz_bf7edb_idx',
            old_name='imports_imp_organiz_4f8887_idx',
        ),
        migrations.RenameIndex(
            model_name='importjobitem',
            new_name='imports_imp_organiz_210707_idx',
            old_name='imports_imp_organiz_f039c5_idx',
        ),
    ]
