BOT_CONVERSA_APP_CODE = 'bot_conversa'
DEFAULT_DISPATCH_BATCH_SIZE = 3
DEFAULT_REMOTE_CONTACT_MAX_PAGES = 25
BOT_CONVERSA_WEBHOOK_API_PREFIX = '/api/v1/webhook'
BOT_CONVERSA_FLOWS_PATH = f'{BOT_CONVERSA_WEBHOOK_API_PREFIX}/flows/'
BOT_CONVERSA_CONTACTS_PATH = f'{BOT_CONVERSA_WEBHOOK_API_PREFIX}/subscriber/'
BOT_CONVERSA_CONTACTS_LIST_PATH = f'{BOT_CONVERSA_WEBHOOK_API_PREFIX}/subscribers/'
BOT_CONVERSA_CONTACT_BY_PHONE_PATH_TEMPLATE = (
    f'{BOT_CONVERSA_WEBHOOK_API_PREFIX}/subscriber/get_by_phone/{{phone}}/'
)
BOT_CONVERSA_SEND_MESSAGE_PATH_TEMPLATE = (
    f'{BOT_CONVERSA_WEBHOOK_API_PREFIX}/subscriber/{{subscriber_id}}/send_message/'
)
BOT_CONVERSA_SEND_FLOW_PATH_TEMPLATE = (
    f'{BOT_CONVERSA_WEBHOOK_API_PREFIX}/subscriber/{{subscriber_id}}/send_flow/'
)
