# Generated by Django 6.0.3 on 2026-03-17 19:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0002_alter_organization_segment_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hubspot_company_id', models.CharField(blank=True, db_index=True, default='', max_length=128)),
                ('name', models.CharField(max_length=255)),
                ('website', models.URLField(blank=True, max_length=255)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('normalized_phone', models.CharField(blank=True, db_index=True, editable=False, max_length=16)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_companies', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companies', to='organizations.organization')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_companies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('name', 'website'),
                'constraints': [models.UniqueConstraint(condition=models.Q(('hubspot_company_id', ''), _negated=True), fields=('organization', 'hubspot_company_id'), name='unique_company_hubspot_id_per_organization')],
            },
        ),
    ]
