# Generated by Django 6.0.3 on 2026-03-16 15:52

import common.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppCatalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.SlugField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('icon_class', models.CharField(default='bi bi-grid-fill', max_length=64)),
                ('supports_api_key', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=100)),
            ],
            options={
                'ordering': ('sort_order', 'name'),
            },
        ),
        migrations.CreateModel(
            name='OrganizationAppInstallation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=16)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installations', to='integrations.appcatalog')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_app_installations', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='app_installations', to='organizations.organization')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_app_installations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('app__sort_order', 'app__name'),
            },
        ),
        migrations.CreateModel(
            name='OrganizationAppCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('credential_type', models.CharField(choices=[('api_key', 'API key')], default='api_key', max_length=32)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('revoked', 'Revoked')], default='active', max_length=16)),
                ('secret_value', common.fields.EncryptedTextField(fallback_purposes=('default',), purpose='app-credential')),
                ('masked_value', models.CharField(max_length=255)),
                ('last_four', models.CharField(blank=True, max_length=4)),
                ('version', models.PositiveIntegerField(default=1)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_app_credentials', to=settings.AUTH_USER_MODEL)),
                ('revoked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revoked_app_credentials', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_app_credentials', to=settings.AUTH_USER_MODEL)),
                ('installation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credentials', to='integrations.organizationappinstallation')),
            ],
            options={
                'ordering': ('installation__app__sort_order', '-version', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='AppCredentialAccessAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.CharField(choices=[('reveal', 'Reveal')], default='reveal', max_length=16)),
                ('outcome', models.CharField(choices=[('success', 'Success'), ('denied', 'Denied'), ('not_found', 'Not found')], max_length=16)),
                ('reason', models.CharField(max_length=64)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=255)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credential_access_audits', to=settings.AUTH_USER_MODEL)),
                ('app', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credential_access_audits', to='integrations.appcatalog')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credential_access_audits', to='organizations.organization')),
                ('credential', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_audits', to='integrations.organizationappcredential')),
                ('installation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_audits', to='integrations.organizationappinstallation')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddConstraint(
            model_name='organizationappinstallation',
            constraint=models.UniqueConstraint(fields=('organization', 'app'), name='unique_organization_app_installation'),
        ),
        migrations.AddIndex(
            model_name='organizationappcredential',
            index=models.Index(fields=['installation', 'status'], name='integration_install_fec8b0_idx'),
        ),
        migrations.AddIndex(
            model_name='organizationappcredential',
            index=models.Index(fields=['credential_type', 'status'], name='integration_credent_568558_idx'),
        ),
        migrations.AddConstraint(
            model_name='organizationappcredential',
            constraint=models.UniqueConstraint(fields=('installation', 'credential_type', 'version'), name='unique_installation_credential_version'),
        ),
        migrations.AddConstraint(
            model_name='organizationappcredential',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('installation', 'credential_type'), name='unique_active_credential_per_installation'),
        ),
        migrations.AddIndex(
            model_name='appcredentialaccessaudit',
            index=models.Index(fields=['organization', 'event_type', 'outcome'], name='integration_organiz_8a49ec_idx'),
        ),
    ]
