# Generated by Django 6.0.3 on 2026-03-16 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0004_translate_app_catalog_metadata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appcredentialaccessaudit',
            name='event_type',
            field=models.CharField(choices=[('reveal', 'Exibicao')], default='reveal', max_length=16),
        ),
        migrations.AlterField(
            model_name='appcredentialaccessaudit',
            name='outcome',
            field=models.CharField(choices=[('success', 'Sucesso'), ('denied', 'Negado'), ('not_found', 'Nao encontrado')], max_length=16),
        ),
        migrations.AlterField(
            model_name='organizationappcredential',
            name='credential_type',
            field=models.CharField(choices=[('api_key', 'Chave de API')], default='api_key', max_length=32),
        ),
        migrations.AlterField(
            model_name='organizationappcredential',
            name='status',
            field=models.CharField(choices=[('active', 'Ativo'), ('inactive', 'Inativo'), ('revoked', 'Revogado')], default='active', max_length=16),
        ),
        migrations.AlterField(
            model_name='organizationappinstallation',
            name='status',
            field=models.CharField(choices=[('active', 'Ativo'), ('inactive', 'Inativo')], default='active', max_length=16),
        ),
    ]
