# Generated by Django 6.0.3 on 2026-03-17 18:13

import common.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_alter_organization_segment_and_more'),
        ('people', '0002_person_bot_conversa_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='email',
            field=common.fields.EncryptedTextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='person',
            name='email_lookup',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
        migrations.AddConstraint(
            model_name='person',
            constraint=models.UniqueConstraint(condition=models.Q(('email_lookup', ''), _negated=True), fields=('organization', 'email_lookup'), name='unique_person_email_per_organization'),
        ),
    ]
