# Generated by Django 6.0.3 on 2026-03-17 19:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
        ('organizations', '0002_alter_organization_segment_and_more'),
        ('people', '0003_person_email_person_email_lookup_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='persons', to='companies.company'),
        ),
        migrations.AddField(
            model_name='person',
            name='hubspot_contact_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=128),
        ),
        migrations.AddConstraint(
            model_name='person',
            constraint=models.UniqueConstraint(condition=models.Q(('hubspot_contact_id', ''), _negated=True), fields=('organization', 'hubspot_contact_id'), name='unique_person_hubspot_contact_id_per_organization'),
        ),
    ]
