# Generated by Codex for Apollo person imports.
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('people', '0004_person_company_person_hubspot_contact_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='apollo_person_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='person',
            name='normalized_phone',
            field=models.CharField(blank=True, db_index=True, default='', editable=False, max_length=16),
        ),
        migrations.AlterField(
            model_name='person',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.RemoveConstraint(
            model_name='person',
            name='unique_person_phone_per_organization',
        ),
        migrations.AddConstraint(
            model_name='person',
            constraint=models.UniqueConstraint(
                condition=~models.Q(('normalized_phone', '')),
                fields=('organization', 'normalized_phone'),
                name='unique_person_phone_per_organization',
            ),
        ),
        migrations.AddConstraint(
            model_name='person',
            constraint=models.UniqueConstraint(
                condition=~models.Q(('apollo_person_id', '')),
                fields=('organization', 'apollo_person_id'),
                name='unique_person_apollo_person_id_per_organization',
            ),
        ),
    ]
