# Generated by Django 6.0.3 on 2026-03-16 16:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bot_conversa', '0001_initial'),
        ('integrations', '0002_seed_app_catalog'),
        ('organizations', '0001_initial'),
        ('people', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='botconversacontact',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bot_conversa_contacts', to='people.person'),
        ),
        migrations.AddField(
            model_name='botconversacontact',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_bot_conversa_contacts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='botconversaflowcache',
            name='installation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bot_conversa_flows', to='integrations.organizationappinstallation'),
        ),
        migrations.AddField(
            model_name='botconversaflowcache',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bot_conversa_flows', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='botconversaflowdispatch',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_bot_conversa_dispatches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='botconversaflowdispatch',
            name='flow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dispatches', to='bot_conversa.botconversaflowcache'),
        ),
        migrations.AddField(
            model_name='botconversaflowdispatch',
            name='installation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bot_conversa_flow_dispatches', to='integrations.organizationappinstallation'),
        ),
        migrations.AddField(
            model_name='botconversaflowdispatch',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bot_conversa_flow_dispatches', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='botconversaflowdispatch',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_bot_conversa_dispatches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='botconversaflowdispatchitem',
            name='contact_link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispatch_items', to='bot_conversa.botconversacontact'),
        ),
        migrations.AddField(
            model_name='botconversaflowdispatchitem',
            name='dispatch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='bot_conversa.botconversaflowdispatch'),
        ),
        migrations.AddField(
            model_name='botconversaflowdispatchitem',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bot_conversa_flow_dispatch_items', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='botconversaflowdispatchitem',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bot_conversa_flow_dispatch_items', to='people.person'),
        ),
        migrations.AddField(
            model_name='botconversasynclog',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bot_conversa_sync_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='botconversasynclog',
            name='contact_link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sync_logs', to='bot_conversa.botconversacontact'),
        ),
        migrations.AddField(
            model_name='botconversasynclog',
            name='installation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bot_conversa_sync_logs', to='integrations.organizationappinstallation'),
        ),
        migrations.AddField(
            model_name='botconversasynclog',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bot_conversa_sync_logs', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='botconversasynclog',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bot_conversa_sync_logs', to='people.person'),
        ),
        migrations.AddConstraint(
            model_name='botconversacontact',
            constraint=models.UniqueConstraint(fields=('organization', 'installation', 'person'), name='unique_bot_conversa_contact_per_person'),
        ),
        migrations.AddConstraint(
            model_name='botconversacontact',
            constraint=models.UniqueConstraint(fields=('organization', 'external_subscriber_id'), name='unique_bot_conversa_subscriber_per_organization'),
        ),
        migrations.AddConstraint(
            model_name='botconversaflowcache',
            constraint=models.UniqueConstraint(fields=('organization', 'installation', 'external_flow_id'), name='unique_bot_conversa_flow_per_installation'),
        ),
        migrations.AddIndex(
            model_name='botconversaflowdispatch',
            index=models.Index(fields=['organization', 'status'], name='bot_convers_organiz_aae2a8_idx'),
        ),
        migrations.AddIndex(
            model_name='botconversaflowdispatchitem',
            index=models.Index(fields=['dispatch', 'status'], name='bot_convers_dispatc_d10fa8_idx'),
        ),
        migrations.AddIndex(
            model_name='botconversaflowdispatchitem',
            index=models.Index(fields=['organization', 'status'], name='bot_convers_organiz_29766e_idx'),
        ),
        migrations.AddConstraint(
            model_name='botconversaflowdispatchitem',
            constraint=models.UniqueConstraint(fields=('dispatch', 'normalized_phone'), name='unique_bot_conversa_dispatch_phone'),
        ),
        migrations.AddIndex(
            model_name='botconversasynclog',
            index=models.Index(fields=['organization', 'action', 'outcome'], name='bot_convers_organiz_cabcb7_idx'),
        ),
    ]
