# Generated by Django 6.0.3 on 2026-03-16 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_conversa', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botconversacontact',
            name='sync_status',
            field=models.CharField(choices=[('synced', 'Sincronizado'), ('pending', 'Pendente'), ('stale', 'Desatualizado'), ('error', 'Erro'), ('archived', 'Arquivado')], default='pending', max_length=16),
        ),
        migrations.AlterField(
            model_name='botconversaflowcache',
            name='status',
            field=models.CharField(choices=[('active', 'Ativo'), ('draft', 'Rascunho'), ('paused', 'Pausado'), ('unknown', 'Desconhecido')], default='unknown', max_length=16),
        ),
        migrations.AlterField(
            model_name='botconversaflowdispatch',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendente'), ('running', 'Em andamento'), ('completed', 'Concluido'), ('completed_with_errors', 'Concluido com erros'), ('failed', 'Falhou')], default='pending', max_length=32),
        ),
        migrations.AlterField(
            model_name='botconversaflowdispatchitem',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendente'), ('running', 'Em andamento'), ('success', 'Sucesso'), ('failed', 'Falhou'), ('skipped', 'Ignorado')], default='pending', max_length=16),
        ),
        migrations.AlterField(
            model_name='botconversasynclog',
            name='action',
            field=models.CharField(choices=[('lookup', 'Consulta'), ('create', 'Criacao'), ('link', 'Vinculo')], max_length=16),
        ),
        migrations.AlterField(
            model_name='botconversasynclog',
            name='outcome',
            field=models.CharField(choices=[('success', 'Sucesso'), ('not_found', 'Nao encontrado'), ('error', 'Erro')], max_length=16),
        ),
    ]
