# Generated by Django 6.0.3 on 2026-03-17 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_conversa', '0004_backfill_person_bot_conversa_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botconversasynclog',
            name='outcome',
            field=models.CharField(choices=[('success', 'Sucesso'), ('not_found', 'Não encontrado'), ('error', 'Erro')], max_length=16),
        ),
    ]
