# Generated by Django 6.0.3 on 2026-03-18 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_conversa', '0005_alter_botconversasynclog_outcome'),
    ]

    operations = [
        migrations.AddField(
            model_name='botconversaflowdispatch',
            name='max_delay_seconds',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='botconversaflowdispatch',
            name='min_delay_seconds',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
