# Generated by Django 6.0.3 on 2026-03-18 19:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_conversa', '0006_botconversaflowdispatch_max_delay_seconds_and_more'),
        ('integrations', '0006_update_gmail_catalog_metadata'),
        ('organizations', '0002_alter_organization_segment_and_more'),
        ('people', '0005_person_apollo_person_id_and_optional_phone'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BotConversaTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('external_tag_id', models.CharField(max_length=128)),
                ('name', models.CharField(max_length=255)),
                ('last_synced_at', models.DateTimeField()),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('installation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bot_conversa_tags', to='integrations.organizationappinstallation')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bot_conversa_tags', to='organizations.organization')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='BotConversaPersonTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('external_subscriber_id', models.CharField(blank=True, max_length=128)),
                ('sync_status', models.CharField(choices=[('synced', 'Sincronizado'), ('error', 'Erro')], default='synced', max_length=16)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('last_error_message', models.CharField(blank=True, max_length=255)),
                ('remote_payload', models.JSONField(blank=True, default=dict)),
                ('contact_link', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tag_links', to='bot_conversa.botconversacontact')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_bot_conversa_person_tags', to=settings.AUTH_USER_MODEL)),
                ('installation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bot_conversa_person_tags', to='integrations.organizationappinstallation')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bot_conversa_person_tags', to='organizations.organization')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bot_conversa_person_tags', to='people.person')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_bot_conversa_person_tags', to=settings.AUTH_USER_MODEL)),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person_links', to='bot_conversa.botconversatag')),
            ],
            options={
                'ordering': ('tag__name', 'person__first_name', 'person__last_name'),
            },
        ),
        migrations.AddConstraint(
            model_name='botconversatag',
            constraint=models.UniqueConstraint(fields=('organization', 'installation', 'external_tag_id'), name='unique_bot_conversa_tag_per_installation'),
        ),
        migrations.AddIndex(
            model_name='botconversapersontag',
            index=models.Index(fields=['organization', 'tag'], name='bot_convers_organiz_ed599b_idx'),
        ),
        migrations.AddIndex(
            model_name='botconversapersontag',
            index=models.Index(fields=['organization', 'person'], name='bot_convers_organiz_6d85bc_idx'),
        ),
        migrations.AddConstraint(
            model_name='botconversapersontag',
            constraint=models.UniqueConstraint(fields=('organization', 'person', 'tag'), name='unique_bot_conversa_tag_per_person'),
        ),
    ]
