# Generated by Django 6.0.3 on 2026-03-18 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_conversa', '0007_botconversatag_botconversapersontag_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botconversaflowdispatch',
            name='max_delay_seconds',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='botconversaflowdispatch',
            name='min_delay_seconds',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
