# Generated by Django 6.0.3 on 2026-03-19 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_conversa', '0008_alter_botconversaflowdispatch_max_delay_seconds_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botconversaflowdispatch',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendente'), ('running', 'Em andamento'), ('paused', 'Pausado'), ('completed', 'Concluido'), ('completed_with_errors', 'Concluido com erros'), ('failed', 'Falhou')], default='pending', max_length=32),
        ),
    ]
