# Generated by Codex for Apollo integration.

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('companies', '0002_apollo_company_fields'),
        ('integrations', '0001_initial'),
        ('organizations', '0002_alter_organization_segment_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApolloUsageSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fetched_at', models.DateTimeField()),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('credits_used', models.PositiveIntegerField(blank=True, null=True)),
                ('credits_remaining', models.PositiveIntegerField(blank=True, null=True)),
                ('rate_limit_per_minute', models.PositiveIntegerField(blank=True, null=True)),
                ('rate_limit_per_hour', models.PositiveIntegerField(blank=True, null=True)),
                ('rate_limit_per_day', models.PositiveIntegerField(blank=True, null=True)),
                ('installation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apollo_usage_snapshots', to='integrations.organizationappinstallation')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apollo_usage_snapshots', to='organizations.organization')),
            ],
            options={
                'ordering': ('-fetched_at', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='ApolloCompanySyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(choices=[('import', 'Importacao'), ('sync_to_hubspot', 'Sincronizacao HubSpot')], max_length=32)),
                ('outcome', models.CharField(choices=[('success', 'Sucesso'), ('error', 'Erro')], max_length=16)),
                ('message', models.CharField(blank=True, max_length=255)),
                ('remote_payload', models.JSONField(blank=True, default=dict)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='apollo_company_sync_logs', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='apollo_sync_logs', to='companies.company')),
                ('installation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apollo_company_sync_logs', to='integrations.organizationappinstallation')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apollo_company_sync_logs', to='organizations.organization')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
