# Generated by Django 6.0.3 on 2026-03-18 20:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apollo_integration', '0001_initial'),
        ('integrations', '0006_update_gmail_catalog_metadata'),
        ('organizations', '0002_alter_organization_segment_and_more'),
        ('people', '0005_person_apollo_person_id_and_optional_phone'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApolloPeopleEnrichmentJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('completed', 'Concluido'), ('webhook_pending', 'Aguardando webhook'), ('completed_with_errors', 'Concluido com erros')], default='completed', max_length=32)),
                ('fetch_phone', models.BooleanField(default=False)),
                ('webhook_token', models.CharField(blank=True, default='', max_length=128)),
                ('total_people', models.PositiveIntegerField(default=0)),
                ('processed_people', models.PositiveIntegerField(default=0)),
                ('success_people', models.PositiveIntegerField(default=0)),
                ('failed_people', models.PositiveIntegerField(default=0)),
                ('started_at', models.DateTimeField()),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('request_payload', models.JSONField(blank=True, default=dict)),
                ('last_webhook_payload', models.JSONField(blank=True, default=dict)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='apollo_people_enrichment_jobs', to=settings.AUTH_USER_MODEL)),
                ('installation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apollo_people_enrichment_jobs', to='integrations.organizationappinstallation')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apollo_people_enrichment_jobs', to='organizations.organization')),
            ],
            options={
                'ordering': ('-started_at', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='ApolloPeopleEnrichmentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('apollo_person_id', models.CharField(db_index=True, max_length=128)),
                ('status', models.CharField(choices=[('completed', 'Concluido'), ('waiting_webhook', 'Aguardando webhook'), ('failed', 'Falhou')], default='completed', max_length=32)),
                ('requested_phone', models.BooleanField(default=False)),
                ('email_enriched', models.BooleanField(default=False)),
                ('phone_enriched', models.BooleanField(default=False)),
                ('error_message', models.CharField(blank=True, default='', max_length=255)),
                ('request_payload', models.JSONField(blank=True, default=dict)),
                ('response_payload', models.JSONField(blank=True, default=dict)),
                ('webhook_payload', models.JSONField(blank=True, default=dict)),
                ('webhook_received_at', models.DateTimeField(blank=True, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apollo_people_enrichment_items', to='organizations.organization')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apollo_enrichment_items', to='people.person')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='apollo_integration.apollopeopleenrichmentjob')),
            ],
            options={
                'ordering': ('created_at',),
                'constraints': [models.UniqueConstraint(fields=('job', 'apollo_person_id'), name='unique_apollo_people_enrichment_item_per_job')],
            },
        ),
    ]
